export const ISO_CURRENCY_DATA = [
  { symbol: "$", iso_code: "USD", country: "United States Dollar", country_code: "US" },
  { symbol: "€", iso_code: "EUR", country: "Euro", country_code: "EU" },
  { symbol: "£", iso_code: "GBP", country: "British Pound Sterling", country_code: "GB" },
  { symbol: "¥", iso_code: "JPY", country: "Japanese Yen", country_code: "JP" },
  { symbol: "₹", iso_code: "INR", country: "Indian Rupee", country_code: "IN" },
  { symbol: "₩", iso_code: "KRW", country: "South Korean Won", country_code: "KR" },
  { symbol: "₽", iso_code: "RUB", country: "Russian Ruble", country_code: "RU" },
  { symbol: "₺", iso_code: "TRY", country: "Turkish Lira", country_code: "TR" },
  { symbol: "₴", iso_code: "UAH", country: "Ukrainian Hryvnia", country_code: "UA" },
  { symbol: "₪", iso_code: "ILS", country: "Israeli New Shekel", country_code: "IL" },
  { symbol: "₦", iso_code: "NGN", country: "Nigerian Naira", country_code: "NG" },
  { symbol: "R$", iso_code: "BRL", country: "Brazilian Real", country_code: "BR" },
  { symbol: "฿", iso_code: "THB", country: "Thai Baht", country_code: "TH" },
  { symbol: "₫", iso_code: "VND", country: "Vietnamese Dong", country_code: "VN" },
  { symbol: "₱", iso_code: "PHP", country: "Philippine Peso", country_code: "PH" },
  { symbol: "₡", iso_code: "CRC", country: "Costa Rican Colón", country_code: "CR" },
  { symbol: "₲", iso_code: "PYG", country: "Paraguayan Guarani", country_code: "PY" },
  { symbol: "₸", iso_code: "KZT", country: "Kazakhstani Tenge", country_code: "KZ" },
  { symbol: "ƒ", iso_code: "ANG", country: "Netherlands Antillean Guilder", country_code: "AN" },
  { symbol: "₭", iso_code: "LAK", country: "Lao Kip", country_code: "LA" },
  { symbol: "₮", iso_code: "MNT", country: "Mongolian Tögrög", country_code: "MN" },
  { symbol: "৳", iso_code: "BDT", country: "Bangladeshi Taka", country_code: "BD" },
  { symbol: "៛", iso_code: "KHR", country: "Cambodian Riel", country_code: "KH" },
  { symbol: "฿", iso_code: "BTC", country: "Bitcoin", country_code: "BTC" },
  { symbol: "د.إ", iso_code: "AED", country: "United Arab Emirates Dirham", country_code: "AE" },
  { symbol: "د.ب", iso_code: "BHD", country: "Bahraini Dinar", country_code: "BH" },
  { symbol: "ر.س", iso_code: "SAR", country: "Saudi Riyal", country_code: "SA" },
  { symbol: "د.ك", iso_code: "KWD", country: "Kuwaiti Dinar", country_code: "KW" },
  { symbol: "د.ع", iso_code: "IQD", country: "Iraqi Dinar", country_code: "IQ" },
  { symbol: "ر.ق", iso_code: "QAR", country: "Qatari Riyal", country_code: "QA" },
  { symbol: "﷼", iso_code: "IRR", country: "Iranian Rial", country_code: "IR" },
  { symbol: "₨", iso_code: "PKR", country: "Pakistani Rupee", country_code: "PK" },
  { symbol: "₨", iso_code: "NPR", country: "Nepalese Rupee", country_code: "NP" },
  { symbol: "₨", iso_code: "MUR", country: "Mauritian Rupee", country_code: "MU" },
  { symbol: "₨", iso_code: "LKR", country: "Sri Lankan Rupee", country_code: "LK" },
  { symbol: "Z$", iso_code: "ZWL", country: "Zimbabwean Dollar", country_code: "ZW" },
  { symbol: "Kč", iso_code: "CZK", country: "Czech Koruna", country_code: "CZ" },
  { symbol: "kr", iso_code: "SEK", country: "Swedish Krona", country_code: "SE" },
  { symbol: "kr", iso_code: "NOK", country: "Norwegian Krone", country_code: "NO" },
  { symbol: "kr", iso_code: "DKK", country: "Danish Krone", country_code: "DK" },
  { symbol: "Rp", iso_code: "IDR", country: "Indonesian Rupiah", country_code: "ID" },
  { symbol: "RM", iso_code: "MYR", country: "Malaysian Ringgit", country_code: "MY" },
  { symbol: "A$", iso_code: "AUD", country: "Australian Dollar", country_code: "AU" },
  { symbol: "C$", iso_code: "CAD", country: "Canadian Dollar", country_code: "CA" },
  { symbol: "NZ$", iso_code: "NZD", country: "New Zealand Dollar", country_code: "NZ" },
  { symbol: "S$", iso_code: "SGD", country: "Singapore Dollar", country_code: "SG" },
  { symbol: "HK$", iso_code: "HKD", country: "Hong Kong Dollar", country_code: "HK" },
  { symbol: "MX$", iso_code: "MXN", country: "Mexican Peso", country_code: "MX" },
  { symbol: "R", iso_code: "ZAR", country: "South African Rand", country_code: "ZA" },
  { symbol: "S/.", iso_code: "PEN", country: "Peruvian Sol", country_code: "PE" },
  { symbol: "CHf", iso_code: "CHF", country: "Swiss Franc", country_code: "CH" },
  { symbol: "Ft", iso_code: "HUF", country: "Hungarian Forint", country_code: "HU" },
  { symbol: "L", iso_code: "ALL", country: "Albanian Lek", country_code: "AL" },
  { symbol: "Kz", iso_code: "AOA", country: "Angolan Kwanza", country_code: "AO" },
  { symbol: "Bs.", iso_code: "VES", country: "Venezuelan Bolívar Soberano", country_code: "VE" },
  { symbol: "Q", iso_code: "GTQ", country: "Guatemalan Quetzal", country_code: "GT" },
  { symbol: "T$", iso_code: "TOP", country: "Tongan Paʻanga", country_code: "TO" },
  { symbol: "Ar", iso_code: "MGA", country: "Malagasy Ariary", country_code: "MG" },
  { symbol: "MAD", iso_code: "MAD", country: "Moroccan Dirham", country_code: "MA" },
  { symbol: "CFA", iso_code: "XAF", country: "Central African CFA Franc", country_code: "CM,CF,GA,TD,GQ,CG" },
  { symbol: "CFA", iso_code: "XOF", country: "West African CFA Franc", country_code: "BJ,BF,CI,GW,ML,NE,SN,TG" },
  { symbol: "MVR", iso_code: "MVR", country: "Maldivian Rufiyaa", country_code: "MV" },
  { symbol: "BTN", iso_code: "BTN", country: "Bhutanese Ngultrum", country_code: "BT" },
];