export const ISO_CURRENCY_DATA = [
  { symbol: "$", iso_code: "USD", country: "United States Dollar" },
  { symbol: "€", iso_code: "EUR", country: "Euro" },
  { symbol: "£", iso_code: "GBP", country: "British Pound Sterling" },
  { symbol: "¥", iso_code: "JPY", country: "Japanese Yen" },
  { symbol: "₹", iso_code: "INR", country: "Indian Rupee" },
  { symbol: "₩", iso_code: "KRW", country: "South Korean Won" },
  { symbol: "₽", iso_code: "RUB", country: "Russian Ruble" },
  { symbol: "₺", iso_code: "TRY", country: "Turkish Lira" },
  { symbol: "₴", iso_code: "UAH", country: "Ukrainian Hryvnia" },
  { symbol: "₪", iso_code: "ILS", country: "Israeli New Shekel" },
  { symbol: "₦", iso_code: "NGN", country: "Nigerian Naira" },
  { symbol: "R$", iso_code: "BRL", country: "Brazilian Real" },
  { symbol: "฿", iso_code: "THB", country: "Thai Baht" },
  { symbol: "₫", iso_code: "VND", country: "Vietnamese Dong" },
  { symbol: "₱", iso_code: "PHP", country: "Philippine Peso" },
  { symbol: "₡", iso_code: "CRC", country: "Costa Rican Colón" },
  { symbol: "₲", iso_code: "PYG", country: "Paraguayan Guarani" },
  { symbol: "₸", iso_code: "KZT", country: "Kazakhstani Tenge" },
  { symbol: "ƒ", iso_code: "ANG", country: "Netherlands Antillean Guilder" },
  { symbol: "₭", iso_code: "LAK", country: "Lao Kip" },
  { symbol: "₮", iso_code: "MNT", country: "Mongolian Tögrög" },
  { symbol: "৳", iso_code: "BDT", country: "Bangladeshi Taka" },
  { symbol: "៛", iso_code: "KHR", country: "Cambodian Riel" },
  { symbol: "฿", iso_code: "BTC", country: "Bitcoin" }, // Same symbol as Thai Baht
  { symbol: "د.إ", iso_code: "AED", country: "United Arab Emirates Dirham" },
  { symbol: "د.ب", iso_code: "BHD", country: "Bahraini Dinar" },
  { symbol: "ر.س", iso_code: "SAR", country: "Saudi Riyal" },
  { symbol: "د.ك", iso_code: "KWD", country: "Kuwaiti Dinar" },
  { symbol: "د.ع", iso_code: "IQD", country: "Iraqi Dinar" },
  { symbol: "ر.ق", iso_code: "QAR", country: "Qatari Riyal" },
  { symbol: "﷼", iso_code: "IRR", country: "Iranian Rial" },
  { symbol: "₨", iso_code: "PKR", country: "Pakistani Rupee" },
  { symbol: "₨", iso_code: "NPR", country: "Nepalese Rupee" },
  { symbol: "₨", iso_code: "MUR", country: "Mauritian Rupee" },
  { symbol: "₨", iso_code: "LKR", country: "Sri Lankan Rupee" },
  { symbol: "Z$", iso_code: "ZWL", country: "Zimbabwean Dollar" },
  { symbol: "Kč", iso_code: "CZK", country: "Czech Koruna" },
  { symbol: "kr", iso_code: "SEK", country: "Swedish Krona" },
  { symbol: "kr", iso_code: "NOK", country: "Norwegian Krone" },
  { symbol: "kr", iso_code: "DKK", country: "Danish Krone" },
  { symbol: "Rp", iso_code: "IDR", country: "Indonesian Rupiah" },
  { symbol: "RM", iso_code: "MYR", country: "Malaysian Ringgit" },
  { symbol: "A$", iso_code: "AUD", country: "Australian Dollar" },
  { symbol: "C$", iso_code: "CAD", country: "Canadian Dollar" },
  { symbol: "NZ$", iso_code: "NZD", country: "New Zealand Dollar" },
  { symbol: "S$", iso_code: "SGD", country: "Singapore Dollar" },
  { symbol: "HK$", iso_code: "HKD", country: "Hong Kong Dollar" },
  { symbol: "MX$", iso_code: "MXN", country: "Mexican Peso" },
  { symbol: "R", iso_code: "ZAR", country: "South African Rand" },
  { symbol: "S/.", iso_code: "PEN", country: "Peruvian Sol" },
  { symbol: "CHf", iso_code: "CHF", country: "Swiss Franc" },
  { symbol: "Ft", iso_code: "HUF", country: "Hungarian Forint" },
  { symbol: "L", iso_code: "ALL", country: "Albanian Lek" },
  { symbol: "Kz", iso_code: "AOA", country: "Angolan Kwanza" },
  { symbol: "Bs.", iso_code: "VES", country: "Venezuelan Bolívar" },
  { symbol: "Q", iso_code: "GTQ", country: "Guatemalan Quetzal" },
  { symbol: "T$", iso_code: "TOP", country: "Tongan Paʻanga" },
  { symbol: "Ar", iso_code: "MGA", country: "Malagasy Ariary" },
  { symbol: "MAD", iso_code: "MAD", country: "Moroccan Dirham" },
]